name: Build
on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
      - uses: actions/checkout@v3
        with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
          
      - name: Setup NodeJS
      - uses: actions/setup-node@v1
        with:
          node-version: 11

      - name: Install dependencies
        run: yarn install
        
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
